/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Main CALM Vector inference engine */
export class Calm {
  /** Create a new untrained model */
  constructor(dim: number, hidden: number)
  /** Load model from serialized bytes */
  static fromBytes(dim: number, hidden: number, bytes: Buffer): Calm
  /** Encode text to vector */
  encode(text: string): Array<number>
  /** Predict next vector */
  step(z: Array<number>): Array<number>
  /** Multi-step prediction */
  steps(z: Array<number>, n: number): Array<Array<number>>
  /** Get model dimension */
  getDim(): number
}

/** Compute cosine similarity between two vectors */
export function cosineSimilarity(a: Array<number>, b: Array<number>): number

/** Compute MSE between two vectors */
export function mse(pred: Array<number>, target: Array<number>): number

/** Compute precision@k */
export function precisionAtK(retrieved: Array<string>, relevant: Array<string>, k: number): number

/** Compute recall@k */
export function recallAtK(retrieved: Array<string>, relevant: Array<string>, k: number): number

/** Hash-based text encoding */
export function hashEmbed(text: string, dim: number): Array<number>
